### ISSUE TITLE
minor bug: 'z is not converted back

### ISSUE THREAD

**Issue by taylor-bsg** [bespoke-silicon-group/bsg_sv2v#6]
https://github.com/bespoke-silicon-group/bsg_sv2v/blob/2d645dfd49ec570f63b8669b01900fa4ddfd450c/examples/bsg_concentrate_static/bsg_concentrate_static.v#L34

**Comment by stdavids** [comment]
Addressed in PR #7

**Comment by stdavids** [comment]
PR #7 Merged
